# Generated by Django 2.0.1 on 2018-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='text',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passage',
            name='title',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
