# Generated by Django 2.0.1 on 2018-02-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180210_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='pub_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
