# Generated by Django 2.0.1 on 2018-02-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_passage_pub_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='type1',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='passage',
            name='type2',
            field=models.CharField(default='无', max_length=50),
        ),
        migrations.AlterField(
            model_name='passage',
            name='type3',
            field=models.CharField(default='无', max_length=50),
        ),
    ]
