# Generated by Django 2.0.1 on 2018-02-19 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_sign', '0002_auto_20180219_1415'),
        ('blogs', '0005_auto_20180216_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='评论内容')),
                ('pub_time', models.DateTimeField(verbose_name='发表时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
        migrations.AlterField(
            model_name='passage',
            name='pub_time',
            field=models.DateTimeField(verbose_name='发表时间'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='text',
            field=models.CharField(max_length=2000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='title',
            field=models.CharField(max_length=30, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='type1',
            field=models.CharField(default='无', max_length=50, verbose_name='标签1'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='type2',
            field=models.CharField(default='无', max_length=50, verbose_name='标签2'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='type3',
            field=models.CharField(default='无', max_length=50, verbose_name='标签3'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Passage', verbose_name='所属文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', verbose_name='作者'),
        ),
    ]
