# Generated by Django 2.0.1 on 2018-02-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180219_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', to_field='username', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', to_field='username', verbose_name='作者'),
        ),
    ]
