# Generated by Django 2.0.1 on 2018-02-20 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20180220_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_sign.User', verbose_name='作者'),
        ),
    ]
