# Generated by Django 2.0.1 on 2018-02-20 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20180220_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='passage',
            new_name='passage_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='passage',
            old_name='username',
            new_name='username_id',
        ),
    ]
